// <auto-generated />
using System;
using CoronaApp_DbInfo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoronaApp_DbInfo.Migrations
{
    [DbContext(typeof(CoronavirusCertificatesDbContext))]
    partial class CoronavirusCertificatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoronaApp_DbInfo.Models.CertificateDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CertificateId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DiseaseCode")
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDateUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MedicalProduct")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RawCertificateData")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("TotalDoses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VaccinationDateUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Vaccine")
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("CertificatesData");
                });
#pragma warning restore 612, 618
        }
    }
}
